[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 8080
  port = 8888
  publish = "dist"
  autoLaunch = true

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[context.production.environment]
  NODE_ENV = "production"
